kind: pipeline
type: docker
name: {{cookiecutter.project_slug}}-ci

trigger:
  event:
    - push
    - pull_request

steps:
  - name: setup
    image: python:3.11
    commands:
      - pip install --upgrade pip
      - pip install .
      - pip install .[dev]

  - name: lint
    image: python:3.11
    commands:
      - pip install tox
      - tox -e lint

  - name: typing
    image: python:3.11
    commands:
      - pip install tox
      - tox -e type

  - name: pytest
    image: python:3.11
    commands:
      - pip install tox
      - tox -e py311